import express from "express";
import { Router } from "express";
import { register,login ,logout,getOtherUsers} from "../controllers/userController.js";
import isAuthenticated from "../middlewares/isAuthenticated.js";
const router = Router();
router.route("/register").post(register);
router.route("/login").post(login);
router.route("/logout").get(logout);
router.route("/getOtherUsers").get(isAuthenticated,getOtherUsers);
export default router;